### ISSUE TITLE
Missing man directories in "slim" variants causes some packages to fail to install

### ISSUE THREAD

**Issue by mithrandi** [debuerreotype/debuerreotype#10]
For example, `postgresql-client-9.4` installs an alternative for `psql.1` resulting in this failure to install (`apt-get install postgresql-client` in a `debian:jessie-slim` container):

```
Setting up postgresql-client-9.4 (9.4.12-0+deb8u1) ...                     
update-alternatives: using /usr/share/postgresql/9.4/man/man1/psql.1.gz to provide /usr/share/man/man1/psql.1.gz (psql.1.gz) in auto mode
update-alternatives: error: error creating symbolic link `/usr/share/man/man1/psql.1.gz.dpkg-tmp': No such file or directory
dpkg: error processing package postgresql-client-9.4 (--configure): 
 subprocess installed post-installation script returned error exit status 2
dpkg: dependency problems prevent configuration of postgresql-client:
 postgresql-client depends on postgresql-client-9.4; however:
  Package postgresql-client-9.4 is not configured yet. 
                                                                                                                                                           
dpkg: error processing package postgresql-client (--configure):       
 dependency problems - leaving unconfigured
```

Leaving the empty directories behind should be enough to fix this, I think.

**Comment by tianon** [comment]
This has been discussed a bit, and left as a bit of an intentional wart so that you (as the user of the image) get to be aware that a package you're trying to install might be leaving files in a directory which is supposed to be purged.

It comes up often enough that I'm starting to waver on that point, though.  Perhaps the majority of packages are well-behaved?

This behavior of `update-alternatives` exploding is amusing however, because once the target directory exists, `update-alternatives` will no-op immediately since it recognizes that the source file doesn't exist.

**Comment by eigood** [comment]
``FROM debian:stretch`` works, ``FROM debian:stretch-slim`` does not, with no other changes.  Makes me lean towards the -slim tooling being broken.

Doesn't policy say certain directories need to exist?  Does it make assumptions about number-based children of higher level locations?

In this particular case, perhaps postgresql-client only accidentally worked, as one of it's dependents just happened to install a man-page into man1.  A similar problem could occur if all earlier packages just had all their man-pages removed by each separate maintainer, such that nothing would be installed into man1/.

I'm not certain which way the bug should go.

**Comment by tianon** [comment]
I think https://www.debian.org/doc/debian-policy/ch-docs.html is the
relevant section of policy -- it doesn't seem to say anything about any of
the directories being _required_ to exist; only that they're the place to
put man pages.

**Comment by tianon** [comment]
To add a little extra information from some re-testing today, this command errors out in both jessie and stretch, but not in unstable, so the bit of code in `update-alternatives` which currently causes the failure in stable and oldstable is fixed in unstable. :tada:

**Comment by yosifkit** [comment]
Updated Debian Policy link: https://www.debian.org/doc/debian-policy/#manual-pages.

**Comment by j16sdiz** [comment]
The `libc-bin` and `libpam-runtime` package create the `man1` directory comes with "Priority: required".
The debian policy reads:

> The following priority levels are recognized by the Debian package management tools.
> 
> required
> Packages which are necessary for the proper functioning of the system (usually, this means that dpkg functionality depends on these packages). Removing a required package may cause your system to become totally broken and you may not even be able to use dpkg to put things back, so only do so if you know what you are doing.

So, yes, they are required by the policy.

**Comment by tianon** [comment]
That's a bit of a stretch -- we're not removing the packages, but simply removing some unnecessary documentation files that they include, which makes this a gray area.

**Comment by j16sdiz** [comment]
Well... You can't remove random bits from a package and still call it installed, can you?

Back in 2001, there was an effort to move all doc from "/usr/doc" to "/usr/share/doc". The -devel list have some debate on this. That migration took a policy change and two release to finish, because they decided all files in required packages are required.

For small distro like this, it is unavoidable to remove some files. 
When packages break because of this, either push for a policy change or just put the empty directory back .

**Comment by gabegorelick** [comment]
For anyone else running into this, since the issue is just that the /usr/share/man{1-8} directories are missing, you can just create them and everything should work, as documented in many of the linked issues: 

```bash
for i in {1..8}; do mkdir -p "/usr/share/man/man$1"; done
```

**Comment by nicolaiskogheim** [comment]
> ```shell
> for i in {1..8}; do mkdir -p "/usr/share/man/man$1"; done
> ```

Typo: The variable should be `$i`, not `$1`.

```bash
for i in {1..8}; do mkdir -p "/usr/share/man/man$i"; done
```

**Comment by gabegorelick** [comment]
> Typo: The variable should be $i, not $1

🤦‍♂️ Yes, sorry.

**Comment by paplorinc** [comment]
Or `for i in $(seq 1 8); do mkdir -p "/usr/share/man/man$i"; done`, if `{1..8}` is not supported

**Comment by james-crowley** [comment]
@yosifkit and @tianon Any updates with this being fixed in `stable`? I saw you guys mention that `unstable` does not have this issue. Has `unstable` been prompted to an "official"l tags like `buster` or `bullseye`? I am running into issues with this on AdoptOpenJDK images since we started offering `debian-slim` based images. 

The fix posted above about generating the `man#` folders work but is not a clean fix.

**Comment by george-hopkins** [comment]
> To add a little extra information from some re-testing today, this command errors out in both jessie and stretch, but not in unstable, so the bit of code in `update-alternatives` which currently causes the failure in stable and oldstable is fixed in unstable. 

@tianon The installation of `openjdk-11-jre-headless` (one of the affected packages) still fails on `debian:unstable-slim`:
```text
Setting up openjdk-11-jre-headless:amd64 (11.0.8+10-1) ...
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/java to provide /usr/bin/java (java) in auto mode
update-alternatives: error: error creating symbolic link '/usr/share/man/man1/java.1.gz.dpkg-tmp': No such file or directory
dpkg: error processing package openjdk-11-jre-headless:amd64 (--configure):
 installed openjdk-11-jre-headless:amd64 package post-installation script subprocess returned error exit status 2
```
Is there something else that needs to be done to get the fixed version?

**Comment by tianon** [comment]
Darn, looks like whatever made it work for a while is now reverted (or only happens in certain edge cases?).

**Comment by SuperSandro2000** [comment]
I could reproduce it with:

```
docker pull debian:unstable-slim
docker run -it debian:unstable-slim
apt update
apt install openjdk-11-jre-headless
```

**Comment by berrange** [comment]
Is there any agreement on the right long term fix for this issue ?  I've just hit it with openjdk-11-jre-headless in both debian:10-slim and debian:sid-slim containers and its frustrating for users of the containers to have to add special case workarounds prior to installing certain packages.

Should the /usr/share/man/man* directory layout be preserved as empty dirs in the -slim images, or do the individual affected packages need to be identified and fixed to explicitly cope with missing man page directories ?

**Comment by simevo** [comment]
also with node-babel7: https://bugs.debian.org/979551

**Comment by tianon** [comment]
I've merged a workaround for this in https://github.com/debuerreotype/debuerreotype/pull/116 which I don't love, but will live with.  Barring any major issues, it'll be part of the next rebuild of the images.

**Comment by tianon** [comment]
FYI, this fix is included in https://github.com/docker-library/official-images/pull/10730. :smile:

Happy [Debian Day](https://wiki.debian.org/DebianDay)! :tada:

**Comment by tianon** [comment]
I don't plan to revert our workaround (unless/until there's evidence it's no longer necessary), but I saw a comment from the `dpkg` maintainer recently that was very relevant to the policy discussions that happened here, and figured it was worth including in this thread; from https://bugs.debian.org/871420#10:

> Policy requires shipping these files in the packages, it does not require them to be present on the user filesystem. It also mentions in §12.3 that no package can expect the existence of any files under /usr/share/doc, which I've always understood as allowing local admins to remove the entire hierarchy w/o consequence.

**Comment by tianon** [comment]
As of today's Debian Policy release (version 4.7.1.0), this is now officially clarified.

https://lists.debian.org/debian-devel-announce/2025/02/msg00004.html

> ```
> 12.1
>     Packages (other than manpage readers) must not require the existence
>     of any files under /usr/share/man.
> 
> 12.2
>     Packages (other than info readers) must not require the existence of
>     any files in /usr/share/info.
> ```

https://www.debian.org/doc/debian-policy/ch-docs.html

> Packages (other than manual page readers) must not require the existence of any files in `/usr/share/man/` in order to function. A package that optionally displays its own manual pages, such as to provide user help, must fail gracefully if the manual pages aren’t installed.

> Packages (other than info readers) must not require the existence of any files in `/usr/share/info/` in order to function.

> Packages must not require the existence of any files in `/usr/share/doc/` in order to function. [6](https://www.debian.org/doc/debian-policy/ch-docs.html#id16) Any files that are used or read by programs but are also useful as stand alone documentation should be installed elsewhere, such as under `/usr/share/package/`, and then included via symbolic links in `/usr/share/doc/package`.

> [[6](https://www.debian.org/doc/debian-policy/ch-docs.html#id6)]
> The system administrator should be able to delete files in `/usr/share/doc/` without causing any programs to break.
